
services:
  db:
    container_name: mydb
    image: mysql:8.0
    restart: on-failure
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internation
      MYSQL_USER: sheru
      MYSQL_PASSWORD: Shreyans@2801
    networks:
      - app-network
    ports:
      - 33061:3306
    volumes:
      - db-data:/var/lib/mysql

  backend:
    restart: always
    image: hudson123456/secure-sync-backend:0.0.1
    container_name: spring-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3306/internation
      SPRING_DATASOURCE_USERNAME: sheru
      SPRING_DATASOURCE_PASSWORD: Shreyans@2801
    networks:
      - app-network
    ports:
      - 8085:8080

  frontend:
    restart: on-failure
    image: hudson123456/secure-sync-frontend:0.0.1
    networks:
      - app-network
    ports:
      - 5173:80

networks:
  app-network:

volumes:
  db-data:
    driver: local